#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config split_ratio		0.5
bspc config border_width	2
bspc config window_gap		5

WG=$(bspc config window_gap)
for SIDE in bottom left right; do bspc config ${SIDE}_padding -${WG}; done
for SIDE in bottom left right; do bspc config ${SIDE}_monocle_padding ${WG}; done

bspc config borderless_monocle	true
bspc config gapless_monocle		true

bspc config normal_border_color "#333840"
bspc config active_border_color "#333840"
bspc config focused_border_color "#98a6b3"

sxhkd &
light-locker &
udiskie &
$HOME/.config/polybar/launch.sh

if [ -x $HOME/.autostart.sh ]; then
	$HOME/.autostart.sh
fi
